SEASONS_ANALYSIS = {
    "Winter": {
        "True Winter": {
            "Hair": [
                "Ashy brown",
                "Black brown",
                "Black with blue undertones",
                "Silver",
                "Occasionally blondes",
            ],
            "Eyes": [
                "Blue",
                "Gray",
                "Violet",
                "Light brown",
                "Icy hazel",
                "Clear brown",
                "Black/brown",
            ],
            "Skin": [
                "Very pale beige",
                "Pale beige",
                "Pale olive",
                "Rosy beige",
                "Black (no golden hues)",
            ],
            "Best Colors": ["Primary colors", "Pure pigments", "Fully saturated"],
            "Worst Colors": ["Golden and brown hues", "Warm soft tones"],
            "Hue": "Cool",
            "Value": "Medium",
            "Chroma": "Medium High",
            "Celebrities": [
                "Liv Tyler",
                "Marian Cotillard",
                "Jennifer Connelly",
                "Jamie Lee Curtis",
                "Brook Shields",
            ],
        },
        "Bright Winter": {
            "Skin": ["Cool undertones", "Light olive complexions"],
            "Hair": [
                "Medium brown to black with blue or ashy tints",
                "Potentially bright red",
            ],
            "Eyes": ["Bright blue", "Green", "Clear gray hazel", "Rich brown"],
            "Best Colors": [
                "Vivid hues with cool undertones",
                "Intense pigments",
                "Icy colors",
            ],
            "Worst Colors": ["Dusty and muted tones", "Warmer shades"],
            "Hue": "Cool/Neutral",
            "Value": "Medium",
            "Chroma": "High",
            "Celebrities": [
                "Megan Fox",
                "Ziyi Zhang",
                "Courtney Cox",
                "Camila Mendes",
                "Krysten Ritter",
            ],
        },
        "Dark Winter": {
            "Skin": ["Olive undertones", "Deep cool undertones"],
            "Hair": ["Medium to dark brown", "Black", "Silver gray"],
            "Eyes": ["Dark hazel", "Dark brown", "Black"],
            "Best Colors": [
                "High-saturation colors",
                "Rich primary colors",
                "Pure pigments",
            ],
            "Worst Colors": [
                "Earthy tones",
                "Warm nudes",
                "Warm browns",
                "Oranges",
                "Yellows",
            ],
            "Hue": "Cool/Neutral",
            "Value": "Deep",
            "Chroma": "Leans towards bright and clear",
            "Celebrities": [
                "Anne Hathaway",
                "Viola Davis",
                "Archie Panjabi",
                "Monica Belluci",
            ],
        },
    },
    "Summer": {
        "Light Summer": {
            "Skin": [
                "Neutral undertone with a possible rosy hint (most likely burns easily)"
            ],
            "Hair": ["Light to medium ash blonde", "Light ash brown"],
            "Eyes": [
                "Light gray",
                "Light blue",
                "Medium blue",
                "Light green (blue hue)",
            ],
            "Best Colors": ["Light colors that are dusty or powdery"],
            "Worst Colors": ["Dark overpowering colors", "High-saturation warm-tones"],
            "Hue": "Cool/Neutral",
            "Value": "Light",
            "Chroma": "Medium",
            "Celebrities": [
                "Elle Fanning",
                "Margot Robbie",
                "Cate Blanchett",
                "Amy Poehler",
                "Naomi Watts",
            ],
        },
        "Soft Summer": {
            "Skin": ["Light to medium beige", "Light brown with neutral undertones"],
            "Hair": ["Light to medium brown (ash blond tint)"],
            "Eyes": ["Gray", "Blue", "Hazel", "Brown"],
            "Best Colors": ["Soft, muted hues, in the cooler color family"],
            "Worst Colors": ["Neons", "Rich clear colors"],
            "Hue": "Cool/Neutral",
            "Value": "Medium",
            "Chroma": "Soft",
            "Celebrities": [
                "Sarah Jessica Parker",
                "Cara Delevingne",
                "Ellen Pompei",
                "Jennifer Aniston",
                "Rihanna",
            ],
        },
        "Cool Summer": {
            "Skin": [
                "Cool undertones that generally range from medium beige to dark cool brown"
            ],
            "Hair": ["Medium to dark brown with ashy undertones"],
            "Eyes": ["Gray", "Blue", "Slate"],
            "Best Colors": ["Cool hues that are medium to dark in tone"],
            "Worst Colors": ["Warm tones", "Earthy shades", "Warm yellows"],
            "Hue": "Cool",
            "Value": "Medium",
            "Chroma": "Slightly leans towards soft/muted",
            "Celebrities": [
                "Kate Middleton",
                "Allison Williams",
                "Emily Blunt",
                "Emily Deschanel",
            ],
        },
    },
    "Spring": {
        "Light Spring": {
            "Skin": [
                "Fair skin with pink or peachy undertones, may tan, freckles are common"
            ],
            "Hair": [
                "Light to medium gold blonde and brown",
                "Sometimes strawberry blonde",
            ],
            "Eyes": ["Blue", "Green", "Hazel", "Light soft brown"],
            "Best Colors": ["Light, warm, clear colors"],
            "Worst Colors": ["Dark, overpowering colors"],
            "Hue": "Warm/Neutral",
            "Value": "Light",
            "Chroma": "Medium",
            "Celebrities": [
                "Taylor Swift",
                "Scarlett Johansson",
                "Blake Lively",
                "Michelle Williams",
            ],
        },
        "Clear (Bright) Spring": {
            "Skin": ["Porcelain, milky white to golden brown, tans easily"],
            "Hair": [
                "Golden light to dark brown hair, can include copper or auburn tones"
            ],
            "Eyes": ["Bright, clear eye colors: blue, green, light brown"],
            "Best Colors": ["Saturated, warm hues and bright colors"],
            "Worst Colors": ["Nudes", "Dusty-muted pastels"],
            "Hue": "Warm/Neutral",
            "Value": "Medium",
            "Chroma": "Clear, bright",
            "Celebrities": ["Emma Watson", "Mila Jovovich", "Jessica Pare"],
        },
        "True Spring": {
            "Skin": ["Warm toned skin, porcelain shades to light bronze"],
            "Hair": [
                "Strawberry blonde",
                "Golden blonde",
                "Light golden brown",
                "Coppery red",
            ],
            "Eyes": ["Blue", "Light brown", "Dark green", "Light hazel"],
            "Best Colors": ["Vibrant, warm-toned colors"],
            "Worst Colors": ["Cool-toned pastels", "Darker shades"],
            "Hue": "Warm",
            "Value": "Medium",
            "Chroma": "Leans towards Clear and Bright",
            "Celebrities": [
                "Blake Lively",
                "Cameron Diaz",
                "Goldie Hawn",
                "Jayma Mays",
                "Gillian Anderson",
            ],
        },
    },
    "Autumn": {
        "Warm (True) Autumn": {
            "Skin": ["Ivory", "Golden", "Medium brown (all warm undertones)"],
            "Hair": [
                "Medium to Dark Brown with golden tones",
                "Warm auburn",
                "Darker red",
            ],
            "Eyes": ["Light brown", "Green", "Hazel", "Sometimes dark brown (rich)"],
            "Best Colors": ["Rich and muted warm tones (browns, rusts)"],
            "Worst Colors": ["Pastels", "Pastel brights"],
            "Hue": "Warm",
            "Value": "Medium",
            "Chroma": "Medium",
            "Celebrities": [
                "Jessica Alba",
                "Jennifer Lopez",
                "Kate Mara",
                "Julianne Moore",
                "Julia Roberts",
            ],
        },
        "Deep Autumn": {
            "Skin": [
                "Ivory",
                "Golden beige",
                "Medium to rich browns with warm undertones",
            ],
            "Hair": [
                "Medium to dark brown",
                "Brown-black (can have honey or ginger highlights)",
            ],
            "Eyes": ["Dark-blue", "Dark green", "Hazel", "Dark brown", "Brown black"],
            "Best Colors": ["Bold, warm colors with rich pigments"],
            "Worst Colors": ["Dusty colors", "Pastels"],
            "Hue": "Warm/Neutral",
            "Value": "Deep",
            "Chroma": "Muted",
            "Celebrities": [
                "Kendall Jenner",
                "Halle Berry",
                "Natalie Portman",
                "Sofia Vergara",
                "Oprah",
                "Mindy Kaling",
            ],
        },
        "Soft Autumn": {
            "Skin": [
                "Ivory",
                "Tan",
                "Light brown (all with warm or neutral undertones)",
            ],
            "Hair": ["Golden blonde to dark brown (can have ginger highlights)"],
            "Eyes": ["Green", "Hazel", "Blue", "Light brown"],
            "Best Colors": ["Muted warm-toned colors", "Blended colors"],
            "Worst Colors": ["Stark colors (like black)", "High-pigment bright colors"],
            "Hue": "Warm/Neutral",
            "Value": "Leans Light",
            "Chroma": "Soft/Muted",
            "Celebrities": [
                "Gigi Hadid",
                "Gisele Bundchen",
                "Drew Barrymore",
                "Rosie Huntington-Whiteley",
            ],
        },
    },
}
