from enum import Enum


class Seasons(Enum):
    LIGHT_SPRING = "Light Spring"
    WARM_SPRING = "Warm Spring"
    BRIGHT_SPRING = "Bright Spring"
    LIGHT_SUMMER = "Light Summer"
    COOL_SUMMER = "Cool Summer"
    SOFT_SUMMER = "Soft Summer"
    SOFT_AUTUMN = "Soft Autumn"
    WARM_AUTUMN = "Warm Autumn"
    DEEP_AUTUMN = "Deep Autumn"
    DEEP_WINTER = "Deep Winter"
    COOL_WINTER = "Cool Winter"
    BRIGHT_WINTER = "Bright Winter"


SEASONAL_COLORS = {
    Seasons.LIGHT_SPRING: {
        "description": "Light springs have peachy or rosy fair skin that may tan or freckle.  They have golden blonde or brown hair with blue, green, hazel, or even light brown eyes.  They look best in light, warm, clear colors. They should avoid wearing dark or overpowering colors that can wash them out. ",
        "colors": [
            "#A69F45",
            "#7DA07A",
            "#1BB17C",
            "#DC3767",
            "#CE4739",
            "#7A80B5",
            "#27B4C8",
            "#836859",
            "#F0EC71",
            "#CCDF86",
            "#74C7B3",
            "#F0A6B7",
            "#F2A595",
            "#D0D2D5",
            "#72C9DB",
            "#D1BE9E",
        ],
    },
    Seasons.WARM_SPRING: {
        "description": "Warm springs have warm traits in their eyes, skin, and hair.  They have warm porcelain, to light bronze skin with golden blonde hair, strawberry blonde hair, or coppery red hair.  They have light eyes.  They look best in vibrant, warm-toned colors that compliment the glowiness in their complexions. They should avoid cool-toned pastels and darker shades. They look fantastic in oranges and yellows that bring out their warm intensity.",
        "colors": [
            "#ECAB4D",
            "#3B7545",
            "#2E8D80",
            "#D84C63",
            "#B24B42",
            "#745BA3",
            "#2E75B9",
            "#413F40",
            "#E6C568",
            "#90BB53",
            "#49BB74",
            "#EE7F91",
            "#F37E6B",
            "#9C7FB5",
            "#4AA2D6",
            "#6D6660",
        ],
    },
    Seasons.BRIGHT_SPRING: {
        "description": "Bright Springs has a very wide spectrum of possibilities. You will find redheads, brunettes, and blondes. Similarly, you will find people with my coloring (pale brunettes) that are Bright Spring. We tend to think of Bright Springs as tan, glowing beach goddesses with bright green eyes, but the reality is much more expansive. People can be hesitant to type themselves as a Bright Spring because they don’t feel “bright” enough. They think I don’t “glow” more than anyone else I know. But that’s the thing, we all look like normal people out in the world. Bright Springs just shine when they are in their colors, just like every other season. Bright springs have a wide range of skin tones from pale to golden brown and black.   Their hair colors range from blonde to medium, and dark brown and can include some red or copper highlights. Their eye range often has a mix of colors in it with blue, green, brown, and topaz being common. They look best in saturated, warm hues. Generally, they should avoid nudes and muted/dusty pastels as it will wash them out. Bright Springs are high-contrast compared to the rest of the spring family, which lets them embrace bright colors easily. And they also border Bright Winter so they have a bit more coolness seeping into their palette than True Spring.",
        "colors": [
            "#254F92",
            "#2F4579",
            "#235076",
            "#423E65",
            "#644895",
            "#8C62A4",
            "#602884",
            "#018A42",
            "#39B3BE",
            "#1D8682",
            "#53BED1",
            "#00707E",
            "#5C9ACB",
            "#277DBB",
            "#E6475D",
            "#E6648E",
            "#E04673",
            "#BE3161",
            "#91B748",
            "#5B9C34",
            "#31783C",
            "#FDEDA7",
            "#F4CA6E",
            "#E89F46",
            "#E9704D",
            "#EC887E",
            "#E75C48",
            "#D8283D",
        ],
    },
    Seasons.LIGHT_SUMMER: {
        "description": "Light summers have neutral skin that burns easily and can have a rosy tint to it.  Their hair is icy and in the blond or very light brown family.  They have light-colored eyes like blue, green, or gray.  They look best in light colors that are dusty, or powdery. The light colors complement the light tones in their coloring and don’t overpower their delicate features. They should generally avoid dark colors or high-saturation warm tones.",
        "colors": [
            "#F6D087",
            "#2CA17C",
            "#2A8598",
            "#E1465F",
            "#AE5374",
            "#5B5488",
            "#315184",
            "#596774",
            "#F2DAB4",
            "#84CDB2",
            "#75CCDD",
            "#F07182",
            "#F19BB8",
            "#9885BD",
            "#90ADD7",
            "#CCD0D5",
        ],
    },
    Seasons.COOL_SUMMER: {
        "description": "Cool summers have cool or blue undertones to all three characteristics (skin, hair, and eyes). They often have cool or neutral skin tones with grey, blue or slate eyes.  Their hair tones are ashy in nature and range from medium to dark brown (not black). They look best in cool hues that are medium and sometimes dark in the color palette. Their color palette is muted with blue-pink undertones but does not have the shaded quality of Soft Summer. They should avoid warm tones, especially yellow-toned hues or earthy warm shades. Cool Summer’s most important characteristic is “hue”, which is cool and represented in the “true” part of their name. Both sister seasons (soft summer and light summer) are also cool-based. So Cool Summers will not be getting any warmth in the palette. They still get colors like yellow and red in their palette, but they will be created with a blue base, not a yellow one. Cool Summers are like English roses in a beautiful garden. They have a delicate presence and a tranquil feel to their look.",
        "colors": [
            "#A2C1EB",
            "#70AED5",
            "#4675AD",
            "#305587",
            "#9393C3",
            "#665D94",
            "#4D4477",
            "#79C1AA",
            "#148E8D",
            "#339B88",
            "#007958",
            "#71C2E1",
            "#0191A0",
            "#077288",
            "#EA6F8D",
            "#E881A0",
            "#C15372",
            "#92495B",
            "#F6C0D6",
            "#C47598",
            "#963C64",
            "#D6CACA",
            "#BEA59F",
            "#5F4D4F",
            "#BCBFC2",
            "#50575E",
            "#7B989A",
            "#43808F",
        ],
    },
    Seasons.SOFT_SUMMER: {
        "description": "Soft Summers are the shaded side of the summer season so they are muted but have Soft Autumn on one side so we see a bit of warmth creeping in. Your color palette ranges from light stone to charcoal. Compared to Deep Winter, they can handle less depth and saturation, but Soft Summer handles the deepest summer colors of the Summer seasons. Soft summers can have the following characteristics. Soft summers have neutral undertones or blue undertones with a pink tint.  They can also have brown skin tones that have a neutral undertone.  Their hair colors are in the light-to-medium brown color family with ash blond highlights or tints. Soft summers have low contrast between their eyes, hair, and skin.  They look best in soft and muted hues that are more subtle (usually in the cooler color family).  They should generally avoid clear colors that are neon or especially rich, which tends to overwhelm their complexions subtlety. They have a floatiness quality to their coloring as if they might drift away. We can imagine a foggy morning with soft lavender skies and soft gray clouds rolling over the water. They look otherworldly in colors like muted merlot, softened grape, and dusty blues. Soft Summers can look tan. The concept of if you tan you are warm-toned is incorrect. ",
        "colors": [
            "#A0C1EA",
            "#70AED5",
            "#4675AD",
            "#305587",
            "#9492C3",
            "#665D93",
            "#4F4679",
            "#79C1AA",
            "#449882",
            "#2F6A5F",
            "#007958",
            "#71C2E1",
            "#4CB5C6",
            "#077288",
            "#EB859E",
            "#E96885",
            "#C15372",
            "#F4C1D6",
            "#C47598",
            "#92495b",
            "#963C64",
            "#D6CACA",
            "#AA8B8D",
            "#5F4D4F",
            "#929AA5",
            "#6F7B95",
            "#BDC9CB",
            "#7097A2",
        ],
    },
    Seasons.SOFT_AUTUMN: {
        "description": "A soft autumn does not have a lot of contrast between their hair and skin. Their skin tone often has neutral undertones, but can also have more prominent warm undertones.  They look best in muted colors with warm undertones, that pair nicely with their skin tones hue. They also look great in blended colors (not primary).  They should generally avoid stark colors (black), or bright colors (high pigment, like fuchsia, etc) because they tend to make them look sallow. ",
        "colors": [
            "#78AACB",
            "#33618A",
            "#2D4F68",
            "#6D709B",
            "#707EAF",
            "#4D5B82",
            "#414141",
            "#93926A",
            "#A6D1B5",
            "#86BC9C",
            "#5F8D79",
            "#478F85",
            "#247674",
            "#366045",
            "#EFA4A2",
            "#EC827E",
            "#F4C4BA",
            "#E88484",
            "#A24B4A",
            "#6E6A57",
            "#929D7A",
            "#E0B88D",
            "#CCA480",
            "#A47C65",
            "#9E6C61",
            "#694D4F",
            "#F1D48E",
            "#CBB178",
        ],
    },
    Seasons.WARM_AUTUMN: {
        "description": "Warm autumns have the following characteristics. Keep in mind your holistic view of your colorings, because True Autumns have a earthy and harvest quality to their coloring. They are like fall afternoons with fall leaves turning and the pumpkins on the front porch, with caramel apples and soft sun through the clouds. There is earthiness and warmth here. Warm Autumns have warm undertones to their skin and the tone can range from ivory to medium brown.  They typically have hair colors that range from medium to dark brown or red (including auburn) all with golden undertones.  Their eyes are light brown, green, or (green) hazel.  They look amazing in rich and muted warm tones, especially earthy colors like brown and rust.  They should generally avoid pastels or pastel brights that wash them out. Their dominant characteristic is hue (purely warm). So both of their sister seasons Soft Autumn and Dark Autumn will also have warm undertones. Autumns are also muted, so they have a rich rustic quality to the color palette filled with pumpkin oranges, butterscotch, and terracotta. They still have their versions of blues and purples and all other hues, but they are warmed up (with yellow) and toned down (with some gray added). Their palette range has their version of white which is warm or soft or sometimes a light putty beige, to their version of black which is a warm pewter.",
        "colors": [
            "#867C41",
            "#57843D",
            "#2E543D",
            "#20828D",
            "#1F5E6D",
            "#856C9C",
            "#653D60",
            "#E09758",
            "#C56248",
            "#E06450",
            "#B64C34",
            "#E5727D",
            "#8F4345",
            "#ABB175",
            "#F4DBA5",
            "#C1974D",
            "#846D41",
            "#B47C65",
            "#996457",
            "#FDD077",
            "#DFB16B",
            "#C7C089",
            "#E9DCC2",
            "#F4DBA5",
            "#B6A27E",
            "#B9A07A",
            "#928167",
            "#6F5D4F",
        ],
    },
    Seasons.DEEP_AUTUMN: {
        "description": "Deep autumns have the following characteristics as general color combinations. But remember that seasonal color is a holistic approach so you have to look at your entire coloring and how they relate to hue, value, and chroma. Do not just say I have brown hair and brown eyes so I must be Dark Autumn. Dark autumns are autumns first and foremost but they border Dark winter, so they can have a bit of winter’s coolness and crispness seep in. Darkness in color is their primary focus in colors. This does not mean they only have dark colors in their palette but that the range of their colors includes more shades and tones (even if the color is lighter in appearance). Whereas true autumn has your pumpkin oranges, Dark Autumn transitions to the brick reds, and warm redwood colors. There’s richness but still that evident warmth and harvest quality. They are slightly more pigmented than True Autumn because your chroma is going from medium (in True Autumn) to medium-high in Dark Autumn. Deep autumns have warm tones in their hair, eyes, and skin.  They have medium to dark brown hair with golden undertones.  Their eyes are darker, and range from dark blue, dark green, to dark brown or brown/black.  They look amazing in bold, warm colors that are rich in pigment.  They should generally avoid dusty colors or soft pastels as it will make them look washed out. ",
        "colors": [
            "#D4A0BA",
            "#C0789A",
            "#A64E7Ap",
            "#804160",
            "#A09255",
            "#7F723C",
            "#5E5538",
            "#60BAB6",
            "#399896",
            "#105D4B",
            "#2E4740",
            "#2F98B9",
            "#006B81",
            "#034C5E",
            "#E88468",
            "#C16E53",
            "#82473F",
            "#ED8576",
            "#672C37",
            "#903427",
            "#8B2026",
            "#6D5C58",
            "#503E48",
            "#636A3A",
            "#40463A",
            "#D7B569",
            "#B99555",
            "#BE7E57",
        ],
    },
    Seasons.DEEP_WINTER: {
        "description": "Deep winters have a rich and high-contrast feel.  Their skin tones are not purely cool and could even be considered more neutral. Olive complexions are also included in this.  They have dark eyes and dark hair.  They look best in high saturation colors and rich primary colors or pure pigments. They should avoid earthy tones, warm nudes, or warm-toned browns, oranges, and yellows.",
        "colors": [
            "#913D4B",
            "#B690B7",
            "#A96BAA",
            "#773E72",
            "#523955",
            "#5B3443",
            "#3E1C4D",
            "#07776C",
            "#0682B2",
            "#2473A8",
            "#7DB1E4",
            "#6799CC",
            "#2C6FB1",
            "#35426E",
            "#CD3851",
            "#E15564",
            "#893F41",
            "#25A87A",
            "#007255",
            "#205749",
            "#2B381D",
            "#C8DDD4",
            "#BBD2E5",
            "#F7E069",
            "#8DAB41",
            "#637E3D",
            "#EA5E73",
            "#CD4D7D",
        ],
    },
    Seasons.COOL_WINTER: {
        "description": "Cool Winters often have the following characteristics. But remember draping is the only way to be sure. So take the following color guidelines as a very generalized baseline. Because not every Cool Winter will look like Snow White. Cool winters have high contrast between their hair, skin tone, and eyes.  They look best in icy colors and cool colors.  Avoid warm-toned colors for the most flattering pairings.  Pastels all also generally avoided and in their place, you should go for icier colors instead (high saturation + white). Darker values can work well for the Cool winters, so long as they have a cool undertone.",
        "colors": [
            "#B77EB5",
            "#92457F",
            "#7B4889",
            "#5B4D98",
            "#524378",
            "#3C60A8",
            "#434476",
            "#F4CFE4",
            "#EDB9D1",
            "#EA6EA6",
            "#C73C73",
            "#D0639F",
            "#D75C8F",
            "#B73F7B",
            "#2165B0",
            "#39A8E1",
            "#0D7388",
            "#27A6BA",
            "#066555",
            "#018854",
            "#30AA63",
            "#C12A2F",
            "#D02E4F",
            "#FEE607",
            "#FEEA7B",
            "#C8E4EE",
            "#C5DDC1",
            "#BBB",
        ],
    },
    Seasons.BRIGHT_WINTER: {
        "description": "Bright winters can have the following characteristics. But remember that we measure “brightness” by how the fabric drapes react. Can you undertone shine with these “bright” colors? It doesn’t automatically make you look like a super high contrast, brighter than everyone else in the room person. In real life, even the “bright” seasons look relatively normal. In Sci-Art we believe there are red-headed winters and that there are some red-headed Bright Winters with bright red hair and sparkling eyes.. However, other systems will put all redheads in warm seasons. This is the importance of knowing the system that your future analysts uses!",
        "colors": [
            "#9E3283",
            "#823281",
            "#51428D",
            "#48539F",
            "#353D8E",
            "#7465A9",
            "#423B8D",
            "#06984B",
            "#046E3A",
            "#029598",
            "#8CB9E2",
            "#0288CB",
            "#0257A5",
            "#23427A",
            "#EC7F88",
            "#E4414E",
            "#E12540",
            "#EC8BB5",
            "#E32F68",
            "#D6194D",
            "#CE2F85",
            "#F3D0E2",
            "#C0DFCE",
            "#DACAE3",
            "#FBEB80",
            "#FFE56A",
            "#A7C545",
            "#83AB58",
        ],
    },
}

SYSTEM_PROMPT = """
You are an expert on seasonal color analysis, with knowledge based on established systems by Munsell, Itten, Dorr, Jackson, and Caygill. You understand hue, value, and chroma as key determinants of color seasons. You're familiar with the 12 seasonal color types.

Provide concise, assertive responses in JSON format with keys: 
"season": One of the 12 specific seasons. (Light Spring/Warm Spring/Bright Spring/Light Summer/Cool Summer/Soft Summer/Soft Autumn/Warm Autumn/Deep Autumn/Deep Winter/Cool Winter)
/Bright Winter
"characteristics": Key features of the person's coloring
"colorsToSuggest": List of sorted dicts with "name" and "hex_code" of at least 12 colors that complement this season.
"reasonToSuggest": Explanation of why these colors are recommended and how they complement the person's coloring
"colorsToAvoid": List of sorted dicts with "name" and "hex_code" of at least 12 colors that may not flatter this season, avoid extreme colors that are not common clothes colors
"reasonToAvoid": Explanation of why these colors are not recommended and how they might clash with the person's coloring
"content": Concise explanation in correct json format in less than 200 words and correct JSON format of how you determined the season, beginning with "Based on the image provided, you have..." and including how you assessed warm vs. cool undertones, evaluation of contrast levels, assessment of chroma (clarity/brightness vs. softness/mutedness) and any other key factors in your determination.

Your responses should be direct and confident, while acknowledging that in-person professional analysis is the most accurate method. Avoid hedging language unless absolutely necessary.
"""
