<!-- src/routes/analysis/save/+page.svelte -->
<script lang="ts">
  import SwatchSlide from "$lib/components/SwatchSlide.svelte";
  import SvgSpinners3DotsMove from "~icons/svg-spinners/3-dots-move";
  import { onMount } from "svelte";
  import { goto } from "$app/navigation";
  import Alert from "$lib/components/Alert.svelte";

  interface Analysis {
    season: string;
    characteristics: string;
    colorsToSuggest: Color[];
    reasonToSuggest: string;
    colorsToAvoid: Color[];
    reasonToAvoid: string;
    content: string;
  }

  interface Color {
    name: string;
    hexCode: string;
  }

  const seasonTextColors = {
    "Light Spring": "text-[#4A7C59]",
    "Warm Spring": "text-[#8B6E4E]",
    "Bright Spring": "text-[#E37D5E]",
    "Light Summer": "text-[#7C90A0]",
    "Cool Summer": "text-[#5E7C8B]",
    "Soft Summer": "text-[#8B8BAA]",
    "Soft Autumn": "text-[#8B7E66]",
    "Warm Autumn": "text-[#A0522D]",
    "Deep Autumn": "text-[#8B4726]",
    "Deep Winter": "text-[#4A4E69]",
    "Cool Winter": "text-[#4A6670]",
    "Bright Winter": "text-[#5E548E]",
  };
  const disclaimer = {
    title: "Disclaimer",
    description: `This color analysis is generated by <a href="https://claude.ai/" class="font-bold hover:underline">Claude</a>, an AI assistant. While based on color theory principles, it may not be as accurate as an in-person professional analysis. Factors such as image quality, lighting, and screen settings can affect online assessments. For the most precise results, consider consulting with a professional color analyst.`,
  };

  let analysis: Analysis;
  let selectedColor: string = "";
  let seasonTextColor = "";
  let isLoading: boolean = true;
  let croppedImage = "";
  let resultContainer: HTMLElement;

  function handleColorSelected(event: CustomEvent<{ color: string }>) {
    selectedColor = event.detail.color;
  }

  onMount(() => {
    try {
      const croppedImageData = localStorage.getItem("croppedImage");
      const analysisData = localStorage.getItem("analysis");

      if (croppedImageData) {
        croppedImage = "data:image/jpeg;base64," + croppedImageData;
      } else {
        goto("/error");
      }

      if (analysisData) {
        analysis = JSON.parse(analysisData) as Analysis;
        seasonTextColor =
          seasonTextColors[analysis.season as keyof typeof seasonTextColors];
        if (!analysis.characteristics.endsWith(".")) {
          analysis.characteristics += ".";
        }
      } else {
        goto("/error");
      }
    } catch (err) {
      console.error("Error retrieving or parsing data:", err);
    } finally {
      isLoading = false;
    }
  });
</script>

<div
  class="mx-auto flex min-h-screen w-full flex-col items-center justify-center px-8 py-4 font-serif md:w-4/5 md:py-8 lg:w-1/2"
  bind:this={resultContainer}
>
  {#if isLoading}
    <SvgSpinners3DotsMove class="text-3xl text-muted-foreground" />
  {:else}
    <h1 class="w-full text-center">Your Personal Color Analysis</h1>
    <div
      class="flex h-fit w-3/4 max-w-sm flex-col items-center justify-center rounded-xl border bg-primary-foreground p-4 md:w-full"
    >
      <div class="relative w-full">
        <img src={croppedImage} alt="Preview" class="w-full rounded-lg" />
        <span
          class="absolute bottom-0 left-0 h-1/6 w-full rounded-b-lg transition-colors duration-200 ease-in-out"
          style="background-color: {selectedColor};"
        />
      </div>
    </div>
    <div class="my-2 flex h-fit flex-col items-center justify-center md:my-4">
      <h2 class="{seasonTextColor} text-center italic">
        {analysis.season}
      </h2>
      <p class="text-center max-sm:hidden">
        {analysis.characteristics}
      </p>
      <p>
        {analysis.content}
      </p>
      <h2 class="text-center italic">Recommended Colors</h2>
      <p>
        {analysis.reasonToSuggest}
      </p>
      <div class="mb-8 w-full">
        <SwatchSlide
          colors={analysis.colorsToSuggest}
          on:colorSelected={handleColorSelected}
        />
      </div>
      <h2 class="text-center italic">Colors to Avoid</h2>
      <p>
        {analysis.reasonToAvoid}
      </p>
      <div class="mb-4 w-full">
        <SwatchSlide
          colors={analysis.colorsToAvoid}
          on:colorSelected={handleColorSelected}
        />
      </div>
      <span class="mt-4 lg:mt-8">
        <Alert {...disclaimer} />
      </span>
    </div>
  {/if}
  <!-- TODO: Share Button, Save Button -->
</div>
