<script lang="ts">
  import * as Tabs from "$lib/components/ui/tabs";
  import { fade, fly } from "svelte/transition";
  import SwatchSlide from "$lib/components/SwatchSlide.svelte";
  import SvgSpinners3DotsMove from "~icons/svg-spinners/3-dots-move";
  import Alert from "$lib/components/Alert.svelte";
  import { quadInOut } from "svelte/easing";
  import { Button } from "$lib/components/ui/button";
  import { Home, Share, Save } from "lucide-svelte";
  import html2canvas from "html2canvas";
  import { onDestroy, onMount } from "svelte";
  import { goto } from "$app/navigation";
  import { error } from "@sveltejs/kit";
  import { seasonsData } from "$lib/data/seasonsData";
  import { Seasons } from "$lib/types/seasons";
  interface Analysis {
    season: Seasons;
    characteristics: string;
    colorsToSuggest: Color[];
    reasonToSuggest: string;
    colorsToAvoid: Color[];
    reasonToAvoid: string;
    content: string;
    textColor: string;
  }

  interface Color {
    name: string;
    hexCode: string;
  }

  const disclaimer = {
    title: "Disclaimer",
    description: `This color analysis is generated by <a href="https://claude.ai/" class="font-bold hover:underline">Claude</a>, an AI assistant. While based on color theory principles, it may not be as accurate as an in-person professional analysis. Factors such as image quality, lighting, and screen settings can affect online assessments. For the most precise results, consider consulting with a professional color analyst.`,
  };

  const navigationTip = {
    title: "Tip",
    description: `Click the tabs to see more information!`,
  };

  const tip = {
    title: "Tip",
    description: `Click on a color swatch to see how it looks on you!`,
  };

  let analysis: Analysis;
  let croppedImage = "";
  let selectedColor: string = "";
  let resultContainer: HTMLElement;
  let isLoading = true;

  let loadingMessages = [
    "Generating color analysis",
    "Adjusting white balance for perfect neutrals",
    "Compensating for sneaky ambient lighting",
    "Decoding your skin's secret hues",
    "Solving the RGB rubik's cube",
    "Debating warm vs. cool tones",
    "Painting your perfect palette",
    "Banishing unflattering shades",
    "Preparing the color forecast",
  ];
  let currentMessageIndex = 0;
  let messageInterval: ReturnType<typeof setInterval> | undefined;
  let isVisible = true;

  $: currentMessage = loadingMessages[currentMessageIndex];
  let transitionDuration = 5000;

  function updateMessage() {
    isVisible = false;
    setTimeout(() => {
      currentMessageIndex = (currentMessageIndex + 1) % loadingMessages.length;
      isVisible = true;
    }, transitionDuration / 2);
  }

  async function getAnalysis() {
    const croppedImageData =
      typeof localStorage !== "undefined"
        ? localStorage.getItem("croppedImage")
        : null;

    if (!croppedImageData) {
      error(404, "No image data found");
    }

    const response = await fetch("/api/images/analysis", {
      method: "POST",
      body: JSON.stringify({ base64Image: croppedImageData }),
      headers: {
        "Content-Type": "application/json",
      },
    });

    if (!response.ok) {
      const errorData = await response.json();
      throw new Error(errorData.error || "Failed to fetch analysis");
    }

    const data = await response.json();
    const textColor = seasonsData[data.season as Seasons]?.textColor;
    data.textColor = textColor;

    localStorage.setItem("analysis", JSON.stringify(data));
    return data;
  }

  function handleColorSelected(event: CustomEvent<{ color: string }>) {
    selectedColor = event.detail.color;
  }

  function handleShare() {
    if (navigator.share) {
      navigator
        .share({
          title: "My Personal Color Analysis",
          text: `My color season is ${analysis.season}. Check out my personal color analysis!`,
          url: window.location.href,
        })
        .then(() => {
          console.log("Successfully shared");
        })
        .catch((error) => {
          console.error("Error sharing:", error);
        });
    } else {
      alert(
        "Web Share API is not supported in your browser. You can manually copy the URL to share.",
      );
    }
  }

  async function handleSave() {
    try {
      // Create a new div to hold our save layout
      const saveContainer = document.createElement("div");
      saveContainer.className =
        "mx-auto flex min-h-screen w-full flex-col items-center justify-center px-8 py-4 font-serif md:w-4/5 md:py-8 lg:w-1/2";
      saveContainer.style.position = "absolute";
      saveContainer.style.left = "-9999px";
      document.body.appendChild(saveContainer);

      const colorsToSuggestSwatchSlide = document.getElementById(
        "colorsToSuggestSwatchSlide",
      )!.innerHTML;

      const colorsToAvoidSwatchSlide = document.getElementById(
        "colorsToAvoidSwatchSlide",
      )!.innerHTML;

      const disclaimerContainer = document.getElementById(
        "disclaimer-container",
      )!.innerHTML;

      // Populate the save container with the layout from save page
      saveContainer.innerHTML = `
      <h1 class="w-full text-center">Your Personal Color Analysis</h1>
      <div class="flex h-fit w-3/4 max-w-sm flex-col items-center justify-center rounded-xl border bg-primary-foreground p-4 md:w-full">
        <div class="relative w-full">
          <img src="${croppedImage}" alt="Preview" class="w-full rounded-lg" />
        </div>
      </div>
      <div class="my-2 flex h-fit flex-col items-center justify-center md:my-4">
        <h2 class="${analysis.textColor} text-center italic">
          ${analysis.season}
        </h2>
        <p class="text-center max-sm:hidden">
          ${analysis.characteristics}
        </p>
        <p>
          ${analysis.content}
        </p>
        <h2 class="text-center italic">Recommended Colors</h2>
        <p>
        <div id="colorsToSuggest">
          ${colorsToSuggestSwatchSlide}
        </div>
        </p>
        <div id="colorsToSuggest"></div>
        <h2 class="text-center italic">Colors to Avoid</h2>
        <p>
         ${analysis.reasonToAvoid}
        </p>
        <div id="colorsToAvoid">
          ${colorsToAvoidSwatchSlide}
        </div>
        <div id="disclaimer-container" class="mt-8">
          ${disclaimerContainer}
        </div>
      </div>
    `;

      // Generate the image
      const canvas = await html2canvas(saveContainer, {
        scale: 2,
        useCORS: true,
        logging: false,
        allowTaint: true,
      });

      // Convert to data URL and trigger download
      const dataUrl = canvas.toDataURL("image/png");
      const link = document.createElement("a");
      link.download = "color_analysis.png";
      link.href = dataUrl;
      link.click();

      // Clean up
      document.body.removeChild(saveContainer);
    } catch (error) {
      console.error("Error generating image:", error);
      alert("There was an error generating the image. Please try again.");
    }
  }

  onMount(async () => {
    try {
      messageInterval = setInterval(updateMessage, transitionDuration);

      const localAnalysis = localStorage.getItem("analysis");
      const localCroppedImage = localStorage.getItem("croppedImage");
      if (localAnalysis && localCroppedImage) {
        analysis = JSON.parse(localAnalysis);
        croppedImage = "data:image/jpeg;base64," + localCroppedImage;
      } else {
        analysis = await getAnalysis();
        croppedImage = "data:image/jpeg;base64," + localCroppedImage;
      }
    } catch (error) {
      console.log(error);
      goto("/error");
    } finally {
      isLoading = false;
    }
  });

  onDestroy(() => {
    if (messageInterval) {
      clearInterval(messageInterval);
    }
  });

  function clearLocalStorage() {
    const theme = localStorage.getItem("theme");
    localStorage.clear();
    if (theme) {
      localStorage.setItem("theme", theme);
    }
    goto("/");
  }
</script>

<div
  class="mx-auto flex min-h-screen w-full flex-col items-center justify-center px-8 py-4 font-serif md:w-4/5 md:py-8 lg:w-1/2"
  bind:this={resultContainer}
>
  {#if !isLoading}
    <h1
      class="w-full text-center"
      in:fly={{ y: 50, duration: 500, easing: quadInOut }}
    >
      Your Personal Color Analysis
    </h1>
    <div
      class="flex h-fit w-3/4 max-w-sm flex-col items-center justify-center rounded-xl border bg-primary-foreground p-4 md:w-full"
      in:fly={{ y: 75, duration: 750, easing: quadInOut }}
    >
      <div class="relative w-full">
        <img src={croppedImage} alt="Preview" class="w-full rounded-lg" />
        <span
          class="absolute bottom-0 left-0 h-1/6 w-full rounded-b-lg transition-colors duration-200 ease-in-out"
          style="background-color: {selectedColor};"
        />
      </div>
    </div>
    <div in:fly={{ y: 100, duration: 1000, easing: quadInOut }}>
      <Tabs.Root
        value="analysis"
        class="my-2 flex h-fit flex-col items-center justify-center md:my-4"
      >
        <Tabs.List class="font-sans">
          <Tabs.Trigger value="analysis">Analysis</Tabs.Trigger>
          <Tabs.Trigger value="colorsToSuggest">
            Recommended Colors
          </Tabs.Trigger>
          <Tabs.Trigger value="colorsToAvoid">Colors to Avoid</Tabs.Trigger>
        </Tabs.List>
        <Tabs.Content value="analysis" class="mt-4 lg:mt-8">
          <h2 class="{analysis.textColor} text-center italic">
            {analysis.season}
          </h2>
          <p class="text-center max-sm:hidden">
            {analysis.characteristics}
          </p>
          <p>
            {analysis.content}
          </p>
          <Alert {...navigationTip} />
        </Tabs.Content>
        <Tabs.Content value="colorsToSuggest" class="mt-4 lg:mt-8">
          <h2 class="text-center italic">Recommended Colors</h2>
          <p>
            {analysis.reasonToSuggest}
          </p>
          <div class="mb-4" id="colorsToSuggestSwatchSlide">
            <SwatchSlide
              colors={analysis.colorsToSuggest}
              on:colorSelected={handleColorSelected}
            />
          </div>
          <Alert {...tip} />
        </Tabs.Content>
        <Tabs.Content value="colorsToAvoid" class="mt-4 lg:mt-8">
          <h2 class="text-center italic">Colors to Avoid</h2>
          <p>
            {analysis.reasonToAvoid}
          </p>
          <div class="mb-4" id="colorsToAvoidSwatchSlide">
            <SwatchSlide
              colors={analysis.colorsToAvoid}
              on:colorSelected={handleColorSelected}
            />
          </div>
          <Alert {...tip} />
        </Tabs.Content>
        <span class="mt-4 lg:mt-8" id="disclaimer-container">
          <Alert {...disclaimer} />
        </span>
      </Tabs.Root>
    </div>
    <div class="mt-4 flex space-x-4 font-sans">
      <Button on:click={handleShare} variant="outline">
        <Share class="mr-2 h-4 w-4" />
        Share
      </Button>
      <Button on:click={handleSave} variant="outline">
        <Save class="mr-2 h-4 w-4" />
        Save
      </Button>

      <Button on:click={clearLocalStorage} variant="outline">
        <Home class="mr-2 h-4 w-4" />
        Go back to home
      </Button>
    </div>
  {:else}
    <SvgSpinners3DotsMove class="text-3xl text-muted-foreground" />
    {#if isVisible}
      <span
        class="font-sans text-muted-foreground"
        transition:fade={{ duration: transitionDuration }}
      >
        {currentMessage}
      </span>
    {/if}
  {/if}
</div>
