<script lang="ts">
  import { fade } from "svelte/transition";
  import { imgSrcStore, analysisStore } from "$lib/stores";
  import SwatchSlide from "$lib/components/SwatchSlide.svelte";
  import SvgSpinners3DotsMove from "~icons/svg-spinners/3-dots-move";
  import GuidanceAlertTriangle from "~icons/guidance/alert-triangle";
  import { get } from "svelte/store";
  import { onMount } from "svelte";

  interface Analysis {
    season: string;
    characteristics: string;
    colorsToSuggest: Color[];
    reasonToSuggest: string;
    colorsToAvoid: Color[];
    reasonToAvoid: string;
    content: string;
  }

  interface Color {
    name: string;
    hexCode: string;
  }

  const disclaimer =
    "While based on color theory principles, it may not be as accurate as an in-person professional analysis. Factors such as image quality, lighting, and screen settings can affect online assessments. For the most precise results, consider consulting with a professional color analyst.";

  let analysis: Analysis;
  let selectedColor: string = "";
  let isLoading: boolean = true;

  function handleColorSelected(event: CustomEvent<{ color: string }>) {
    selectedColor = event.detail.color;
  }

  onMount(() => {
    const analysisData = get(analysisStore);
    if (analysisData) {
      try {
        if (typeof analysisData === "object" && analysisData !== null) {
          analysis = analysisData;
        } else {
          analysis = JSON.parse(analysisData);
        }
      } catch (error) {
        console.error("Error parsing analysis:", error);
      } finally {
        isLoading = false;
      }
    }
  });
</script>

<div
  class="flex min-h-screen w-full flex-col items-center justify-center py-16 text-2xl font-light"
>
  {#if isLoading}
    <SvgSpinners3DotsMove class="text-3xl text-muted-foreground" />
  {:else}
    <div
      class="flex h-fit w-1/2 max-w-sm flex-col items-center justify-center rounded-xl border bg-primary-foreground p-4 md:w-full"
    >
      <div class="relative w-full">
        <img
          src={$imgSrcStore}
          alt="UploadedImage"
          class="w-full rounded-lg"
          in:fade
        />
        <span
          class="absolute bottom-0 left-0 h-1/6 w-full rounded-b-lg transition-colors duration-200 ease-in-out"
          in:fade
          style="background-color: {selectedColor};"
        />
      </div>
    </div>

    <div
      class="mx-auto flex flex-col items-start justify-center px-8 py-4 font-serif md:w-3/4 md:px-16 md:py-8 lg:w-1/2"
      in:fade
    >
      <h1 class="w-full">Your Personal Color Analysis</h1>
      <h2>Your Color Season: {analysis.season}</h2>
      <p>
        {analysis.characteristics}
      </p>
      <h2>Detailed Analysis</h2>
      <p>
        {analysis.content}
      </p>
      <div class="my-8 w-full space-y-4">
        <h2>Recommended Colors</h2>
        <p>
          {analysis.reasonToSuggest}
        </p>
        <SwatchSlide
          colors={analysis.colorsToSuggest}
          on:colorSelected={handleColorSelected}
        />
      </div>
      <div class="my-4 w-full">
        <h2>Colors to Use Sparingly</h2>
        <p>
          {analysis.reasonToAvoid}
        </p>
        <SwatchSlide
          colors={analysis.colorsToAvoid}
          on:colorSelected={handleColorSelected}
        />
      </div>
      <p
        class="mt-4 rounded-2xl border bg-muted p-4 text-base text-muted-foreground"
      >
        This color analysis is generated by
        <a href="https://claude.ai/" class="font-bold hover:underline">Claude</a
        >, an AI assistant.
        {disclaimer}
      </p>
    </div>
  {/if}
  <!-- TODO: Share Button, Save Button -->
</div>
