<script lang="ts">
  import { fade } from "svelte/transition";
  import SwatchSlide from "$lib/components/SwatchSlide.svelte";
  import SvgSpinners3DotsMove from "~icons/svg-spinners/3-dots-move";
  import { onDestroy, onMount } from "svelte";
  import { goto } from "$app/navigation";
  import * as Carousel from "$lib/components/ui/carousel/index.js";
  import Alert from "$lib/components/Alert.svelte";

  interface Analysis {
    season: string;
    characteristics: string;
    colorsToSuggest: Color[];
    reasonToSuggest: string;
    colorsToAvoid: Color[];
    reasonToAvoid: string;
    content: string;
  }

  interface Color {
    name: string;
    hexCode: string;
  }

  const disclaimer = {
    title: "Disclaimer",
    description: `This color analysis is generated by <a href="https://claude.ai/" class="font-bold hover:underline">Claude</a>, an AI assistant. While based on color theory principles, it may not be as accurate as an in-person professional analysis. Factors such as image quality, lighting, and screen settings can affect online assessments. For the most precise results, consider consulting with a professional color analyst.`,
  };
  const navigationTip = {
    title: "Tip",
    description: `Click the arrows to navigate through the analysis.`,
  };
  const tip = {
    title: "Tip",
    description: `Click on a color swatch to see how it looks on you!`,
  };

  let analysis: Analysis;
  let selectedColor: string = "";
  let isLoading: boolean = true;
  let croppedImage = "";

  function handleColorSelected(event: CustomEvent<{ color: string }>) {
    selectedColor = event.detail.color;
  }

  onMount(() => {
    try {
      const croppedImageData = localStorage.getItem("croppedImage");
      const analysisData = localStorage.getItem("analysis");

      if (croppedImageData) {
        croppedImage = "data:image/jpeg;base64," + croppedImageData;
      } else {
        goto("/error");
      }

      if (analysisData) {
        analysis = JSON.parse(analysisData) as Analysis;
      } else {
        goto("/error");
      }
    } catch (err) {
      console.error("Error retrieving or parsing data:", err);
    } finally {
      isLoading = false;
    }
  });
</script>

<div
  class="mx-auto flex min-h-screen w-full flex-col items-center justify-center px-8 py-4 font-serif md:w-4/5 md:py-8 lg:w-1/2"
>
  {#if isLoading}
    <SvgSpinners3DotsMove class="text-3xl text-muted-foreground" />
  {:else}
    <h1 class="w-full text-center">Your Personal Color Analysis</h1>
    <div
      class="flex h-fit w-3/4 max-w-sm flex-col items-center justify-center rounded-xl border bg-primary-foreground p-4 md:w-full"
    >
      <div class="relative w-full">
        <img
          src={croppedImage}
          alt="Preview"
          class="w-full rounded-lg"
          in:fade
        />
        <span
          class="absolute bottom-0 left-0 h-1/6 w-full rounded-b-lg transition-colors duration-200 ease-in-out"
          in:fade
          style="background-color: {selectedColor};"
        />
      </div>
    </div>

    <div
      class="my-4 flex flex-col items-start justify-center max-sm:hidden"
      in:fade
    >
      <Carousel.Root>
        <Carousel.Content>
          <Carousel.Item>
            <h2>Your Color Season: {analysis.season}</h2>
            <p>
              {analysis.characteristics}
            </p>
            <h2>Detailed Analysis</h2>
            <p>
              {analysis.content}
            </p>
            <Alert {...navigationTip} />
          </Carousel.Item>
          <Carousel.Item>
            <h2>Recommended Colors</h2>
            <SwatchSlide
              colors={analysis.colorsToSuggest}
              on:colorSelected={handleColorSelected}
            />
            <p class="mt-4">
              {analysis.reasonToSuggest}
            </p>
            <Alert {...tip} />
          </Carousel.Item>
          <Carousel.Item>
            <h2>Colors to Use Sparingly</h2>
            <SwatchSlide
              colors={analysis.colorsToAvoid}
              on:colorSelected={handleColorSelected}
            />
            <p class="mt-4">
              {analysis.reasonToAvoid}
            </p>
            <Alert {...tip} />
          </Carousel.Item>
        </Carousel.Content>
        <Carousel.Previous />
        <Carousel.Next />
      </Carousel.Root>
    </div>

    <!-- Mobile View -->
    <div
      class="my-4 flex flex-col items-start justify-center md:my-8 md:hidden"
      in:fade
    >
      <h2>Your Color Season: {analysis.season}</h2>
      <p>
        {analysis.characteristics}
      </p>
      <h2>Detailed Analysis</h2>
      <p>
        {analysis.content}
      </p>
      <h2>Recommended Colors</h2>
      <p>
        {analysis.reasonToSuggest}
      </p>
      <div class="mb-4">
        <SwatchSlide
          colors={analysis.colorsToSuggest}
          on:colorSelected={handleColorSelected}
        />
      </div>
      <h2>Colors to Use Sparingly</h2>
      <p>
        {analysis.reasonToAvoid}
      </p>
      <div class="mb-4">
        <SwatchSlide
          colors={analysis.colorsToAvoid}
          on:colorSelected={handleColorSelected}
        />
      </div>
      <Alert {...tip} />
    </div>
    <Alert {...disclaimer} />
  {/if}
  <!-- TODO: Share Button, Save Button -->
</div>
